### PR TITLE
add logic for registration and login forms. 

### PR DESCRIPTION
**Pull request by DevynJohnson**
html code added in script.js and commented out so it can be easily used where needed

### CODE REVIEW

**Comment by DevynJohnson** [comment]
Closing PR, I have made improvements and will open a new PR with the updated code instead.

**Comment by DevynJohnson** [comment]
Reopen PR with updated code.

**Review by Bert0424 — APPROVED** [review]
approved added code for registration and login forms to be updated to main branch

**Comment by AMShegstad** [comment]
Clicking merge since it was approved.

**Pull request merged**
